"""remove_subject_name

Revision ID: 156433e18484
Revises: 574625e14520
Create Date: 2026-06-29 18:13:26.086995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '156433e18484'
down_revision: Union[str, Sequence[str], None] = '574625e14520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_files', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.String(length=11), nullable=True))
        
    op.execute("UPDATE subscriptions SET student_id = '00000000000' WHERE student_id IS NULL")
    
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.alter_column('student_id', existing_type=sa.String(length=11), nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_student_id'), ['student_id'], unique=False)
        batch_op.drop_column('full_name')
        batch_op.drop_column('subject_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_index(batch_op.f('ix_subscriptions_student_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.drop_column('student_id')

    with op.batch_alter_table('exam_files', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
