"""Initial migration

Revision ID: d3941962d7a2
Revises: 
Create Date: 2026-06-04 12:55:02.945543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3941962d7a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('download_link', sa.Text(), nullable=False),
    sa.Column('crawl_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject_code', sa.String(length=50), nullable=True),
    sa.Column('subject_name', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_subject_code'), ['subject_code'], unique=False)

    op.create_table('exam_schedules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exam_file_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('student_name', sa.String(length=255), nullable=True),
    sa.Column('subject_code', sa.String(length=50), nullable=True),
    sa.Column('subject_name', sa.String(length=500), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('exam_time', sa.String(length=100), nullable=True),
    sa.Column('exam_room', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_file_id'], ['exam_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_file_id', 'student_id', 'subject_code', name='_exam_file_student_subject_uc')
    )
    with op.batch_alter_table('exam_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_schedules_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_schedules_student_name'), ['student_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_schedules_subject_code'), ['subject_code'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.BigInteger(), nullable=False),
    sa.Column('exam_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_schedule_id'], ['exam_schedules.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_status'))
        batch_op.drop_index(batch_op.f('ix_email_logs_email'))

    op.drop_table('email_logs')
    with op.batch_alter_table('exam_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_schedules_subject_code'))
        batch_op.drop_index(batch_op.f('ix_exam_schedules_student_name'))
        batch_op.drop_index(batch_op.f('ix_exam_schedules_student_id'))

    op.drop_table('exam_schedules')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_subject_code'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_email'))

    op.drop_table('subscriptions')
    op.drop_table('exam_files')
    # ### end Alembic commands ###
